/**
 * Storage abstraction — the application only ever talks to this interface, so
 * swapping the Docker volume for an Iranian Object Storage (Arvan) later is a
 * provider change, not a rewrite of ads/businesses/showcase/frontend.
 *
 *   today:  User → API → Image Processing → Docker Volume (LocalStorageDriver)
 *   future: User → API → Image Processing → Arvan Object Storage → CDN
 *
 * Keys are opaque, posix-style relative paths (`media/2026/10/<random>.webp`)
 * generated by the API — never user input, never a path from the client.
 */
export const STORAGE_DRIVER = Symbol('STORAGE_DRIVER');

export interface StoredObjectInfo {
  key: string;
  size: number;
  mtimeMs: number;
}

export interface PutOptions {
  /** Overwrite an existing object (thumb regeneration). Default: never. */
  overwrite?: boolean;
  contentType?: string;
}

export interface StorageDriver {
  readonly name: string;
  /** Stores bytes under `key`; resolves with the number of bytes written. */
  put(key: string, data: Buffer, options?: PutOptions): Promise<number>;
  /** Reads an object, or `null` when it does not exist. */
  get(key: string): Promise<Buffer | null>;
  /** Removes an object; missing objects are not an error. */
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /** All objects, optionally below a prefix (used by the orphan sweep). */
  list(prefix?: string): Promise<StoredObjectInfo[]>;
  /** Public URL clients use to fetch the object. */
  url(key: string): string;
}
